### ISSUE TITLE
Nice package!

### ISSUE THREAD

**Issue by bketelsen** [adam-hanna/jwt-auth#1]
Looked through the code and examples, this is a nice looking JWT package.  I do have a suggestion though:  rename the /src directory to /jwt so the package name is jwt.   A package name of "src" is very confusing, and not idiomatic in Go.   I'm looking forward to playing with this.

**Comment by adam-hanna** [comment]
Hi Brian,

Thanks so much for the encouragement.

I'll definitely rename that folder, ASAP. Agreed the name "src" isn't the
best option.

Thanks much for the feedback. Cheers!

Adam Hanna
