### ISSUE TITLE
usage of log instead of myLog in auth-util.go

### ISSUE THREAD

**Issue by Cjdcoy** [adam-hanna/jwt-auth#12]
Hey you used the function `log` instead of using `myLog `line 84-85 of the file `auth-util.go`.
Due to that even if you set the `options.Debug` to false it keeps displaying logs.
It's not a big issue but it can get quite annoying as this the concerned function is called quite often ;)

**Comment by adam-hanna** [comment]
@Cjdcoy sorry didn't see this until just now. Thanks for the report. I'm on it...

**Comment by adam-hanna** [comment]
@Cjdcoy fixed in [v1.2.0](https://github.com/adam-hanna/jwt-auth/releases/tag/v1.2.0)

Thanks again for the report!
