### ISSUE TITLE
Error in Quickstart Example

### ISSUE THREAD

**Issue by p4tin** [adam-hanna/jwt-auth#2]
I did a "go get go get github.com/adam-hanna/jwt-auth/src" then I tried to run the QuickStart example with "go run quickstart.go" and I get the error:

```
# github.com/adam-hanna/jwt-auth/src
../github.com/adam-hanna/jwt-auth/src/jwt.go:20: undefined: jwt.StandardClaims
```

I assume I am missing a library can you tell me what it is?

**Comment by adam-hanna** [comment]
Interesting. Thanks for letting me know.

I'm using [this library.](https://github.com/dgrijalva/jwt-go) It's already in my GOPATH so of course it's working for me.

This is my first go package so I'm still learning how to use package dependancies, etc. I'll try to get this fixed ASAP!

**Comment by adam-hanna** [comment]
[This stackoverflow Q&A helped me to better understand how to include any vendor dependencies.](http://stackoverflow.com/questions/34775722/package-version-management-in-go-1-5)

Thanks for your help. If you clone the most up to date version, everything should be working. Please let me know if there are still any issues.

Cheers!

**Comment by p4tin** [comment]
Ya I realized that I had not updated the dgrijalva/jwt-go library in a while and that was my problem - thanks for the response!!!

**Comment by adam-hanna** [comment]
Great!

I also should have placed it in the vendor folder of my package.

I'm still learning this goLang thing :P

Glad it's working, and thanks for the feedback!

**Comment by p4tin** [comment]
I will create a PR for the README.md to explain the steps I had to take to make it work there was also the fact that I needed to create the keys and place them in the correct directory.

**Comment by adam-hanna** [comment]
Awesome, but I actually may have fixed that in my last update. I think the
example should be fully functional, now.

Adam Hanna

**Comment by p4tin** [comment]
Sent a PR #3 do what you wish with it - it was just a bit more info on how to get started.
