### ISSUE TITLE
Unexported function when work with Gin and Iris

### ISSUE THREAD

**Issue by se77en** [adam-hanna/jwt-auth#5]
[The Auth's process function](https://github.com/adam-hanna/jwt-auth/blob/master/jwt/auth.go#L252) is unexported, so I can't use it when work with Gin and Iris.

**Comment by adam-hanna** [comment]
Thanks!

Also, would love to know how you're integrating with Gin and Iris so I could update the docs!

**Comment by se77en** [comment]
I wrote a [demo](https://gist.github.com/se77en/c5b15a3bc811de0da6240b9c43c93abb) for this. And please note if [this line](https://gist.github.com/se77en/c5b15a3bc811de0da6240b9c43c93abb#file-gin_with_jwt-go-L45)  change to `return` like ReadMe shows, it does nothing and you can still visit the private api, because the c.Next() bring to next handler.

**Comment by adam-hanna** [comment]
Very interesting. I'll take a look!
